### PR TITLE
delta sparql fix

### LINKED ISSUE #42: Delta SPARQL fails if INSERT DATA is huge
Solution is to split up in many inserts, it can still stay in update SPARQL though.

### PR DESCRIPTION
**Pull request by natan-cox-cognizone**

### CODE REVIEW

File: access/src/main/java/zone/cogni/asquare/edit/delta/Delta.java [hunk 1]
```diff
@@ -39,28 +42,30 @@ public Model getModel() {
...
+    if (removeStatements.isEmpty()) return Stream.empty();
 
-    return "DELETE DATA { \n" +
-           convertStatementsToSparql(removeStatements) + "\n" +
-           "} \n";
+    return Lists.partition(removeStatements, PARTITION_SIZE)
+                .stream()
+                .map(statements -> "DELETE DATA { \n" +
+                                   convertStatementsToSparql(statements) + "\n" +
+                                   "} \n");
```
Comment (domivds) [inline access/src/main/java/zone/cogni/asquare/edit/delta/Delta.java]: I would put the ; here, then you don't have to "tweak" the query after you return it

File: access/src/main/java/zone/cogni/asquare/edit/delta/Delta.java [hunk 2]
```diff
@@ -39,28 +42,30 @@ public Model getModel() {
...
+    if (addStatements.isEmpty()) return Stream.empty();
 
-    return "INSERT DATA { \n" +
-           convertStatementsToSparql(addStatements) + "\n" +
-           "} \n";
+    return Lists.partition(addStatements, PARTITION_SIZE)
+                .stream()
+                .map(statements -> "INSERT DATA { \n" +
+                                   convertStatementsToSparql(statements) + "\n" +
+                                   "} \n");
```
Comment (domivds) [inline access/src/main/java/zone/cogni/asquare/edit/delta/Delta.java]: idem

**Review by domivds — APPROVED** [review]
