### PR TITLE
a new a Dataset copy function on DatasetRdfStoreService

### LINKED ISSUE #123: DatasetRdfStoreService should be able to return a Dataset copy

### LINKED ISSUE #125: Method deleteGraph on DatasetRdfStoreService fails

### LINKED ISSUE #126: Method replaceGraph on DatasetRdfStoreService can be faster
Just a small and simple improvement.

### PR DESCRIPTION
**Pull request by natan-cox-cognizone**
fix #123

### CODE REVIEW

File: service/src/main/java/zone/cogni/asquare/service/index/DatasetRdfStoreService.java [hunk 1]
```diff
@@ -68,4 +69,43 @@ public void executeUpdateQuery(String updateQuery) {
...
+    Dataset datasetCopy = DatasetFactory.create();
+
+    try {
+      dataset.getLock().enterCriticalSection(false);
+
+      // copy named models
+      dataset.listNames()
+             .forEachRemaining(name -> {
+               Model namedModel = dataset.getNamedModel(name);
+               datasetCopy.addNamedModel(name, namedModel);
```
Comment (domivds) [inline service/src/main/java/zone/cogni/asquare/service/index/DatasetRdfStoreService.java]: are we sure this doesn't just use the passed model? Then after the copy a modification would happen in dataset and datasetCopy.

File: service/src/main/java/zone/cogni/asquare/service/index/DatasetRdfStoreService.java [hunk 2]
```diff
@@ -68,4 +69,43 @@ public void executeUpdateQuery(String updateQuery) {
...
+   * <p>
+   * The operation runs in a write transaction.
+   * </p>
+   * <p>
+   * It should be noted that this might have a big performance or memory impact when huge datasets are copied.
+   * </p>
+   *
+   * @return a copy of current Dataset
+   */
+  public Dataset copy() {
```
Comment (domivds) [inline service/src/main/java/zone/cogni/asquare/service/index/DatasetRdfStoreService.java:91]: Maybe it might be nice to have somewhere a DatasetHelper class to put such stuff?

**Comment by natan-cox-cognizone** [comment]
fix #125 
fix #126

**Review by domivds — APPROVED** [review]
