### PR TITLE
fix: add namespace when namespace not present

### LINKED ISSUE #148: Shacl generator fails on an "unknown" namespace
make sure a prefix is automatically created

### LINKED ISSUE #149: improve indexing performance by using String and not Resource in CollectionFolder
so it can be used immediately as a string

### PR DESCRIPTION
**Pull request by michielrogissart-cognizone**

### CODE REVIEW

**Comment by natan-cox-cognizone** [comment]
fix #148

File: cube/src/main/java/zone/cogni/asquare/cube/convertor/data2shacl/ShaclGenerator.java [hunk 1]
```diff
@@ -172,8 +172,9 @@ private Resource calculateShapeBasedOnResource(@Nonnull Configuration configurat
 
     String namespacePrefix = shacl.getNsURIPrefix(originalResource.getNameSpace());
     if (namespacePrefix == null) {
-      throw new RuntimeException("no name alternative found for '" + originalResource.getURI() + "':"
-                                 + " please add namespace to prefixes.");
+      long nrTempPrefixes = shacl.getNsPrefixMap().keySet().stream().filter(key -> key.startsWith("ns")).count();
```
Comment (natan-cox-cognizone) [inline cube/src/main/java/zone/cogni/asquare/cube/convertor/data2shacl/ShaclGenerator.java]: hmm, no I think about it, this ok in most cases but what if there was already one or more "ns" prefixes present. the safer option is to find a good starting point and go from there.

roughly like 

```
private int getAvailableNamespaceIndex(...) {
  return shacl.getNsPrefixMap().keySet().stream()
            .filter(key -> key starts with)
            .map(ns -> ns.substring(2))
            .mapToInt(ns -> Integer.toInt(ns))
            .max();
} 
```

**Review by natan-cox-cognizone — CHANGES_REQUESTED** [review]

File: cube/src/main/java/zone/cogni/asquare/cube/convertor/data2shacl/ShaclGenerator.java [hunk 2]
```diff
@@ -172,15 +172,21 @@ private Resource calculateShapeBasedOnResource(@Nonnull Configuration configurat
...
 
     String prefixLocalName = firstPart == null ? namespacePrefix + "_" + localName
                                                : firstPart + "_" + namespacePrefix + "_" + localName;
     return ResourceFactory.createResource(configuration.getShapesNamespace() + prefixLocalName);
   }
 
+  private long getAvailableNamespaceIndex(Model shacl) {
+    return shacl.getNsPrefixMap().keySet().stream()
+            .filter(key-> key.matches("^ns[0123456789]*$"))
+            .count();
```
Comment (natan-cox-cognizone) [inline cube/src/main/java/zone/cogni/asquare/cube/convertor/data2shacl/ShaclGenerator.java]: Unfortunately, count is not a good way of calculating things. what if you have only ns2? @michielrogissart-cognizone

**Review by natan-cox-cognizone — APPROVED** [review]
