### PR TITLE
fix: replaced javassist error for class not found with one from java.lang

### LINKED ISSUE #5: dependency on org.javassist:javassist
class `AsyncUtils` uses `javassist.bytecode.annotation.NoSuchClassError` of javassist library. 

Let's see how we can remove this library dependency.

### PR DESCRIPTION
**Pull request by alexey-lukashov**

### CODE REVIEW

File: service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java [hunk 1]
```diff
@@ -1,6 +1,5 @@
 package zone.cogni.asquare.service.async;
 
-import javassist.bytecode.annotation.NoSuchClassError;
```
Comment (natan-cox-cognizone) [inline service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java:3]: @alexey-lukashov we must also fix build.gradle

**Review by natan-cox-cognizone — CHANGES_REQUESTED** [review]

File: service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java (hunk 1 above)
Comment (alexey-lukashov) [reply service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java:3]: this dependency could be excluded from service project but it will stay in A2 anyway bcos **service projet** imports **application-profile** imports **spring-boot-starter-thymeleaf** imports **javassist**

Comment (alexey-lukashov) [reply service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java:3]: spring-boot-starter-thymeleaf is used for TemplateFactory from application-profile

Comment (natan-cox-cognizone) [reply service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java:3]: yes, true. but with the fix we do not need to explicitly add it gradle anymore.
so, let's remove it. after removing it, dependencies will look like

```
|    |    +--- org.springframework.boot:spring-boot-starter-thymeleaf -> 2.2.9.RELEASE
|    |    |    +--- org.springframework.boot:spring-boot-starter:2.2.9.RELEASE (*)
|    |    |    +--- org.thymeleaf:thymeleaf-spring5:3.0.11.RELEASE
|    |    |    |    +--- org.thymeleaf:thymeleaf:3.0.11.RELEASE
|    |    |    |    |    +--- ognl:ognl:3.1.12
|    |    |    |    |    |    \--- org.javassist:javassist:3.20.0-GA
```

where before it required to be explicit, one of the "root" dependencies

```
+--- org.javassist:javassist -> 3.20.0-GA
+--- org.junit.jupiter:junit-jupiter -> 5.5.2
```

Comment (natan-cox-cognizone) [reply service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java:3]: Index: build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build.gradle b/build.gradle
--- a/build.gradle	(revision 8b4aed3a19d3e42e801ab9c63fe27c31fd8275be)
+++ b/build.gradle	(date 1633126824240)
@@ -95,7 +95,6 @@
       // netflix zuul 2.2.3 is aligned with spring boot 2.2.9!
       dependency("org.springframework.cloud:spring-cloud-starter-netflix-zuul:2.2.3.RELEASE")
       dependency("ognl:ognl:3.1.12") // seems thymeleaf needs this library
-      dependency('org.javassist:javassist:3.20.0-GA')
 
       // test
       dependency('org.assertj:assertj-core:3.16.1')
@@ -455,7 +454,6 @@
     // spring
     implementation('org.springframework.boot:spring-boot-starter-aop')
     implementation('org.springframework.boot:spring-boot-starter-json')
-    implementation('org.javassist:javassist')
 
     // test
     testImplementation('org.junit.jupiter:junit-jupiter')

Comment (natan-cox-cognizone) [reply service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java:3]:
```
Index: build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build.gradle b/build.gradle
--- a/build.gradle	(revision 8b4aed3a19d3e42e801ab9c63fe27c31fd8275be)
+++ b/build.gradle	(date 1633126824240)
@@ -95,7 +95,6 @@
       // netflix zuul 2.2.3 is aligned with spring boot 2.2.9!
       dependency("org.springframework.cloud:spring-cloud-starter-netflix-zuul:2.2.3.RELEASE")
       dependency("ognl:ognl:3.1.12") // seems thymeleaf needs this library
-      dependency('org.javassist:javassist:3.20.0-GA')
 
       // test
       dependency('org.assertj:assertj-core:3.16.1')
@@ -455,7 +454,6 @@
     // spring
     implementation('org.springframework.boot:spring-boot-starter-aop')
     implementation('org.springframework.boot:spring-boot-starter-json')
-    implementation('org.javassist:javassist')
 
     // test
     testImplementation('org.junit.jupiter:junit-jupiter')

```

Comment (alexey-lukashov) [reply service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java:3]: ok fixed, I havent noticed this was included in build.gradle, there is no such deendency in bitbucket version

Comment (natan-cox-cognizone) [reply service/src/main/java/zone/cogni/asquare/service/async/AsyncUtils.java:3]: Indeed. It seems Gradle 7 behaves a bit differently compared to 4 or 5.

**Review by natan-cox-cognizone — APPROVED** [review]

**Review by marianna-tselepi — APPROVED** [review]
