### PR TITLE
switch to Jena SHACL class; also fixed some other deprecations

### LINKED ISSUE #197: Use Jena for SHACL ontology
and not our own code.

### PR DESCRIPTION
**Pull request by natan-cox-cognizone**

### CODE REVIEW

File: service/src/main/java/zone/cogni/asquare/service/rest/model/RestResponse.java [hunk 1]
```diff
@@ -44,10 +44,7 @@ public String getTitle() {
   }
 
   public String getCode() {
-    if (StringUtils.isEmpty(code)) {
-      return "";
-    }
-    return code;
+    return StringUtils.hasText(code) ? code : "";
```
Comment (domivds) [inline service/src/main/java/zone/cogni/asquare/service/rest/model/RestResponse.java]: not sure if we should enforce usage of apache commons lang3 if needed function is available?

**Review by michielrogissart-cognizone — APPROVED** [review]

**Review by domivds — APPROVED** [review]
